### ISSUE TITLE
delivery_shipstation

### ISSUE THREAD

**Issue by max3903** [OCA/delivery-carrier#137]
This module allows you to connect Odoo with ShipStation and create various delivery methods based on the carriers and services supported by ShipStation (http://www.shipstation.com).

As with any delivery method, you can:
* get a delivery price on the sales order
* get the tracking number and shipping documents (label, etc) on the delivery order

**Comment by lasley** [comment]
We have a client that uses Shipstation, so we'd definitely use this one.

Take a look at our [`connector_easypost`](https://github.com/LasLabs/odoo-connector-easypost/pull/16), which I bet contains a lot of the logic that will be needed here. Another important module to note is [`base_partner_validate_address`](https://github.com/OCA/partner-contact/pull/500), which provides some abstract stuff for address validation. 

We ended up having to base our connector_easypost on a bunch of dependencies in order to make everything work - the primary beast being [`stock_package_info`](https://github.com/OCA/stock-logistics-workflow/pull/384). 

The major thing that is still missing IMO is a good way for a human to select the package type and the rate from within the Odoo UI, at the same point that a weight is being selected. I was about to make an RFC here for this (#144) when I noticed your's 😉
