### ISSUE TITLE
[14.0] Can't get producto price to add Correos delivery method in sale order ()

### ISSUE THREAD

**Issue by cramosh** [OCA/delivery-carrier#487]
## Module
delivery_correos_express

## Describe the bug

When you select the correos express shipping method in the sale order Add shippment wizard, the price of the shipment is always set to 0. The price should be the price of the product selected in the shipping method.

## To Reproduce
- Create a new shipping method selecting correos express
- Select the configured product for the shippment whith a price different to 0
- Create a new sale order
- Add shippment
- Select Correos express
- The price of the line should be the price of the product selected in the configuration process and as you can check is 0.

**Comment by hildickethan** [comment]
It applies the correct price if you press the "Get rate" button next to the price after selecting the carrier

This is a common "issue" throughout all carriers that aren't "Fixed" or "based on rules".
Since it expects the carrier to rate the shipment through webservice, it won't put a request like this in an "onchange", so it sets it to 0 and requires a manual button press.

Alternatively, if you use `delivery_price_method` you can configure other carriers to use the "fixed" or "based on rules" methods to calculate the price, with that configured it should refresh the price when selecting the carrier without the need of pressing "Get rate"
